### ISSUE TITLE
Add json output

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/mend_qc#2]
Now outputs 3 files:

readDist.txt (same as it ever was :-)

bam_umend_qc.tsv:
input   uniqMappedNonDupeReadCount      estExonicUniqMappedNonDupeReadCount     qc
readDist.txt    986     854.78  FAIL

bam_umend_qc.json:
{"input":"readDist.txt","uniqMappedNonDupeReadCount":986,"estExonicUniqMappedNonDupeReadCount":854.78,"qc":"FAIL"}

@hbeale @e-t-k comments? changes to variables?

maybe "qc" should become "passed": true/false to conform to json rules

**Comment by hbeale** [comment]
Plan sounds good to me. Here are the replacement variable names for the tsv
and json


uniqMappedNonDupeReadCount -> uniquelyMappedNonDuplicateReads

estExonicUniqMappedNonDupeReadCount -> uniquelyMappedExonicNonDuplicateReads


>> "passed": true/false


how about "exceedsQcThreshold": true/false ? is that as pleasing to json?

**Comment by e-t-k** [comment]
@rcurrie @hbeale I would actually prefer the original names, including a "qc" field of "PASS"/"FAIL", so that it is concordant with json I get when I parse the old readDist.txt_PASS_qc.txt files, which I know I'll still be interacting with.

So Rob, the json as you described it in the first comment is 👌  perfect from my perspective. Holly, I can change the field names for presentation in the summary.html document to be even friendlier than those.

**Comment by hbeale** [comment]
my thinking about improving the names was to make them more consistent with
the overall goals of the package, particularly for any external users.
reviewing them, I think it's a cosmetic change -- the meaning is in the
original names, even if it's not perfectly self-evident. I'm fine with
using the original variable names (uniqMappedNonDupeReadCount and
estExonicUniqMappedNonDupeReadCount)

**Comment by rcurrie** [comment]
Here's the output as of last night:

```
bam_umend_qc.tsv:
input   uniquelyMappedNonDuplicateReads uniquelyMappedExonicNonDuplicateReads   exceedsQCThreshold
readDist.txt    1708    1554.175        FALSE
bam_umend_qc.json
{"input":"readDist.txt","uniquelyMappedNonDuplicateReads":1708,"uniquelyMappedExonicNonDuplicateReads":1554.175,"exceedsQCThreshold":false}
```

All in a new top level folder as this is a separate pipeline now:
```
├── ucsctreehouse-bam-umend-qc-1.1.0-0000000
    │   ├── bam_umend_qc.json
    │   ├── bam_umend_qc.tsv
    │   ├── methods.json
    │   └── readDist.txt
```

@e-t-k I can change the variable names back to the old ones. Note in json its true/false so you get a boolean vs. the tsv which is PASS/FAIL as before.

**Comment by e-t-k** [comment]
@rcurrie Yes, please change the variable names to the old ones. I'm ok with 'qc' being a boolean if you're consuming that information.

**Comment by rcurrie** [comment]
@hbeale, after a side bar with @e-t-k I've made the tsv match the old format and the json conform to it for consistency of parsing.

data/bam_umend_qc.json
::::::::::::::
{"input":"readDist.txt","uniqMappedNonDupeReadCount":986,"estExonicUniqMappedNonDupeReadCount":854.78,"qc":"FAIL"}
::::::::::::::
data/bam_umend_qc.tsv
::::::::::::::
input   uniqMappedNonDupeReadCount      estExonicUniqMappedNonDupeReadCount     qc
readDist.txt    986     854.78  FAIL
