### ISSUE TITLE
Preserve sortedByCoord.md.bam and sortedByCoord.md.bai

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/mend_qc#5]
mini-var-call and other analysis require the marked duplicate bam output of this pipeline vs. that of the rnaseq pipeline. See [#192](https://github.com/UCSC-Treehouse/operations/issues/192) for details.

**Comment by rcurrie** [comment]
@hbeale noticing that for the small test sample the index is much larger then the bam:

-rw-r--r-- 1 rcurrie pawg 197K Apr 17 06:38 sortedByCoord.md.bam
-rw-r--r-- 1 rcurrie pawg 1.4M Apr 17 06:38 sortedByCoord.md.bam.bai

Could this be true for a small file? Just seems like I may have an issue with the creation of these.

**Comment by hbeale** [comment]
Interesting! I don't know. Maybe try re-creating the index file and see if
the new one has the same size and md5? Or if you want to point me to it I
can take a look.
