### ISSUE TITLE
Reference link in Dockerfile no longer exists

### ISSUE THREAD

**Issue by migbro** [UCSC-Treehouse/mend_qc#7]
This file referenced in the Dockerfile: `https://downloads.sourceforge.net/project/rseqc/BED/Human_Homo_sapiens/hg38_GENCODE_v23_basic.bed.gz` no longer exists.  However, I believe one can generate a bed compatible with the reference used for alignment using the table browser from UCSC.

**Comment by hbeale** [comment]
@migbro thanks for catching that. I've added hg38_GENCODE_v23_basic.bed.gz to the repo and modified the docker file to use it.
